### ISSUE TITLE
Error in Building Project (Class Border)

### ISSUE THREAD

**Issue by Legend-DZ** [ahdung/MessageTip#1]
hello there,
thank you for you project ...it's helpfull and look very nice
but i have problem in building this porject
in class border 
_direction is messing and there some errors
can you provide a binnary (.dll) one

thanks in adveance

**Comment by ahdung** [comment]
Okay, here you are:

[MessageTip.zip](https://github.com/ahdung/MessageTip/files/3123362/MessageTip.zip)

I tried to download this project and compile it, everything is fine, actually this dll is compiled from it just now. I'm using VS2017 v15.9.11, I suggest you try it agian use VS2017, if you still meet problem, please show me the error message in detail, thanks.

**Comment by Legend-DZ** [comment]
thanks bro all is fine .
